In [5]:
import numpy as np
x = np.array([[0, 4, 1],
             [3, 2, 4]])
dW = np.zeros((5, 6))
dout = np.array([[[3, 2, 4, 1, 0, 3],
                 [5, 3, 0, 4, 5, 7],
                 [1, 3, 2, 6, 2, 2]],
                [[3, 0, 4, 3, 0, 1],
                 [5, 1, 3, 3, 3, 2],
                [2, 1, 1, 0, 8, 7]]])
np.add.at(dW, x, dout)
print(dW)

[[ 3.  2.  4.  1.  0.  3.]
 [ 1.  3.  2.  6.  2.  2.]
 [ 5.  1.  3.  3.  3.  2.]
 [ 3.  0.  4.  3.  0.  1.]
 [ 7.  4.  1.  4. 13. 14.]]
